[workspace]

members = [
    "mrial_player",
    "mrial_server",
    "libs/mrial_proto"
]

exclude = [ "libs" ]

[workspace.package]
version = "0.1.11"
authors = ["Mahit Mehta", "Marco Ngai"]
license = "GPL-3.0-only"