[package]
name = "mahitm-rd-x11"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { version = "0.3.29", features = ["thread-pool", "executor"]} 
openh264 = "0.4.4"
scrap = "0.5"
tokio = { version = "1.34.0", features = ["full"]}
x264 = { path = "../libs/x264-rs" }
mouse-rs = "0.4.2"
enigo = "0.2.0-rc2"
cfg-if = "0.1"
mrial_proto = { path = "../libs/mrial_proto" }

[target."cfg(target_os = \"linux\")".dependencies] 
libyuv-sys = { path = "../libs/libyuv-sys" }
pipewire = "0.7.2"

[target."cfg(target_os = \"macos\")".dependencies] 
libyuv-sys = { path = "../libs/libyuv-sys" }