[package]
name = "mrial_player"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ffmpeg-next = "6.0.0"
rodio = "0.17.3"
slint = "1.3.2"
# slint = { path = "../libs/slint/api/rs/slint" }
mrial_proto = { path = "../libs/mrial_proto" }
kanal = "0.1.0-pre8"
serde_json = "1.0.96"
serde = { version = "1.0.164", features = ["derive"] }

[build-dependencies] 
slint-build = "1.3.2"
